project_id_env: BNT_CROWDIN_PROJECT_ID
api_token_env: BNT_CROWDIN_API_TOKEN
preserve_hierarchy: true
files:
  - source: /docs/**/*
    translation: /i18n/%locale%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  - source: /i18n/zh-CN/code.json
    translation: /i18n/%locale%/code.json
  