project_id_env: '829144'
api_token_env: BNT_CROWDIN_API_TOKEN
preserve_hierarchy: true
files:
  - source: /docs/**/*
    translation: /i18n/%locale%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  