name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 2 * * *"
    - cron: "0 4 * * *"
    - cron: "0 6 * * *"
    - cron: "0 8 * * *"
    - cron: "0 10 * * *"
    - cron: "0 12 * * *"
    - cron: "0 14 * * *"
    - cron: "0 16 * * *"
    - cron: "0 18 * * *"
    - cron: "0 20 * * *"
    - cron: "0 22 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
      - name: Crowdin action
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          download_translations: true
          pull_request_title: '[BNT] Crowdin Pull request'
        env:
          BNT_CROWDIN_PROJECT_ID: ${{ secrets.BNT_CROWDIN_PROJECT_ID }}
          BNT_CROWDIN_API_TOKEN: ${{ secrets.BNT_CROWDIN_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build website
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4